# Generated by Django 5.0 on 2026-01-02 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (puede ser SKU o código de barras)', max_length=50, unique=True, verbose_name='Código / Referencia')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras para escaneo', max_length=100, null=True, verbose_name='Código de Barras')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('cantidad_minima', models.IntegerField(default=5, help_text='Alerta cuando llegue a este nivel', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('DOCENA', 'Docena'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete'), ('KILO', 'Kilogramo'), ('GRAMO', 'Gramo'), ('LITRO', 'Litro'), ('METRO', 'Metro'), ('PAR', 'Par'), ('JUEGO', 'Juego')], default='UNIDAD', max_length=20, verbose_name='Unidad de Medida')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se compra el producto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra')),
                ('estado', models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('POR_AGOTAR', '🟡 Por Agotarse'), ('AGOTADO', '🔴 Agotado')], default='DISPONIBLE', max_length=20, verbose_name='Estado del Producto')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar', verbose_name='Producto Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('ubicacion', models.CharField(blank=True, help_text='Estante, pasillo, zona, etc.', max_length=100, verbose_name='Ubicación en Bodega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última Salida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categorias.subcategoria', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('cantidad_minima', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('ubicacion', models.CharField(blank=True, help_text='Pasillo, estante, etc.', max_length=100, verbose_name='Ubicación en Sucursal')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='sucursales.sucursal', verbose_name='Sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario por Sucursal',
                'verbose_name_plural': 'Inventarios por Sucursal',
                'ordering': ['sucursal', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Transferencia')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('EN_TRANSITO', '🚚 En Tránsito'), ('RECIBIDA', '✅ Recibida'), ('RECHAZADA', '❌ Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de Transferencia')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='inventario.producto', verbose_name='Producto')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='sucursales.sucursal', verbose_name='Sucursal Destino')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='sucursales.sucursal', verbose_name='Sucursal Origen')),
            ],
            options={
                'verbose_name': 'Transferencia entre Sucursales',
                'verbose_name_plural': 'Transferencias entre Sucursales',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_d18360_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='inventario__codigo__f8dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='inventario__estado_7e7e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariosucursal',
            unique_together={('producto', 'sucursal')},
        ),
    ]
