# Generated by Django 5.0 on 2026-01-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciasucursal',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('EN_TRANSITO', '🚚 En Tránsito'), ('RECIBIDA', '✅ Recibida'), ('RECHAZADA', '❌ Rechazada')], default='EN_TRANSITO', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('SIN_STOCK', 'Sin Stock')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_generada'],
            },
        ),
    ]
