# Generated by Django 5.0 on 2026-01-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_transferenciasucursal_estado_alertainventario'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste de inventario'), ('MERMA', 'Merma/Pérdida'), ('DEVOLUCION', 'Devolución'), ('VENCIDO', 'Producto vencido'), ('ROBO', 'Robo/Hurto'), ('DAÑADO', 'Producto dañado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='sucursales.sucursal'),
        ),
    ]
