# Generated by Django 5.0 on 2026-02-02 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente', max_digits=5, verbose_name='Margen de Ganancia (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se vende el producto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='No se puede vender por debajo de este precio', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta Mínimo'),
        ),
    ]
