# Generated by Django 5.0 on 2026-02-02 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_factura_detallefactura_movimientoinventario_factura'),
        ('sucursales', '0002_sucursal_aplica_impuesto_consumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo / Razón Social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='anulada',
            field=models.BooleanField(default=False, verbose_name='Factura Anulada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='consecutivo',
            field=models.IntegerField(default=1, verbose_name='Consecutivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='enviada_por_email',
            field=models.BooleanField(default=False, verbose_name='Enviada por Email'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_envio_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío Email'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Solo para ventas a crédito', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuesto_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto al Consumo (8%)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TARJETA_DEBITO', '💳 Tarjeta Débito'), ('TARJETA_CREDITO', '💳 Tarjeta Crédito'), ('TRANSFERENCIA', '🏦 Transferencia Bancaria'), ('NEQUI', '📱 Nequi'), ('DAVIPLATA', '📱 Daviplata'), ('CREDITO', '📋 Crédito'), ('OTRO', '🔄 Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Recibido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='prefijo',
            field=models.CharField(default='FAC', max_length=10, verbose_name='Prefijo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (sin impuestos)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='aplica_impuesto',
            field=models.BooleanField(default=False, help_text='Marcar si este producto tiene impuesto al consumo', verbose_name='Aplica Impuesto al Consumo (8%)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total a Pagar'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='inventario.cliente', verbose_name='Cliente'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_c771c3_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='inventario__numero__f8b607_idx'),
        ),
    ]
