# Generated by Django 5.0 on 2026-02-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_cliente_factura_anulada_factura_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='factura',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
