# Generated by Django 5.0 on 2026-02-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        ('inventario', '0007_remove_factura_cliente_remove_detallefactura_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='facturas.factura', verbose_name='Factura Asociada'),
        ),
    ]
