# Generated by Django 5.0 on 2026-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientoinventario_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clase_abc',
            field=models.CharField(choices=[('A', 'Clase A - Productos estrella'), ('B', 'Clase B - Productos importantes'), ('C', 'Clase C - Productos baja rotación')], default='C', max_length=1, verbose_name='Clasificación ABC'),
        ),
    ]
