# Generated by Django 5.0 on 2026-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_clase_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clase_abc',
            field=models.CharField(choices=[('A', 'Clase A - Productos estrella'), ('B', 'Clase B - Productos importantes'), ('C', 'Clase C - Productos baja rotación')], db_index=True, default='C', max_length=1),
        ),
    ]
