# Generated by Django 5.0 on 2026-02-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0003_alter_sucursal_rango_hasta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', '🛒 Venta Realizada'), ('FACTURA_ANULADA', '❌ Factura Anulada'), ('PRODUCTO_CREADO', '📦 Producto Creado'), ('PRODUCTO_EDITADO', '✏️ Producto Editado'), ('PRODUCTO_ELIMINADO', '🗑️ Producto Eliminado'), ('STOCK_AGREGADO', '📈 Stock Agregado'), ('STOCK_DESCONTADO', '📉 Stock Descontado'), ('AJUSTE_INVENTARIO', '⚖️ Ajuste de Inventario'), ('ALERTA_STOCK_BAJO', '⚠️ Stock Bajo'), ('TRANSFERENCIA_CREADA', '🚚 Transferencia Creada'), ('TRANSFERENCIA_ENVIADA', '📤 Transferencia Enviada'), ('TRANSFERENCIA_RECIBIDA', '📥 Transferencia Recibida'), ('GASTO_REGISTRADO', '💸 Gasto Registrado'), ('GASTO_APROBADO', '✅ Gasto Aprobado'), ('GASTO_RECHAZADO', '❌ Gasto Rechazado'), ('GASTO_PENDIENTE', '⏳ Gasto Pendiente'), ('NOMINA_GENERADA', '💰 Nómina Generada'), ('EMPLEADO_CREADO', '👤 Empleado Creado'), ('EMPLEADO_EDITADO', '✏️ Empleado Editado'), ('USUARIO_REGISTRADO', '👤 Usuario Registrado')], max_length=50, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto')),
                ('referencia_id', models.IntegerField(blank=True, null=True, verbose_name='ID Referencia')),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo Referencia')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lectura')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.sucursal', verbose_name='Sucursal')),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
