# Generated by Django 5.0 on 2025-12-29 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sucursal')),
                ('codigo', models.CharField(help_text='Ej: BOD-001, TDA-A, TDA-B', max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('BODEGA', '🏭 Bodega Principal'), ('TIENDA', '🏪 Tienda'), ('PUNTO_VENTA', '🛒 Punto de Venta')], default='TIENDA', max_length=20, verbose_name='Tipo de Sucursal')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='Sucursal Activa')),
                ('es_principal', models.BooleanField(default=False, help_text='Solo puede haber una bodega principal', verbose_name='Es Bodega Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
