# Generated by Django 5.0 on 2026-02-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='aplica_impuesto_consumo',
            field=models.BooleanField(default=False, help_text='Si aplica impuesto del 8% a ciertos productos', verbose_name='Aplica Impuesto al Consumo'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='consecutivo_actual',
            field=models.IntegerField(default=1, help_text='Próximo número de factura', verbose_name='Consecutivo Actual'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='email_facturacion',
            field=models.EmailField(default='sisbaroficial@gmail.com', max_length=254, verbose_name='Email para Facturación'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nit',
            field=models.CharField(default='000000-0', help_text='Número de Identificación Tributaria', max_length=20, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='% Impuesto al Consumo'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='prefijo_factura',
            field=models.CharField(default='FAC', help_text='Ej: FAC, FV, INV', max_length=10, verbose_name='Prefijo de Factura'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rango_desde',
            field=models.IntegerField(default=1, help_text='Número inicial autorizado', verbose_name='Rango Desde'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rango_hasta',
            field=models.IntegerField(default=19547538, help_text='Número final autorizado', verbose_name='Rango Hasta'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='razon_social',
            field=models.CharField(default='AFTM SAS', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='regimen',
            field=models.CharField(default='Responsable de IVA - Régimen Común', max_length=50, verbose_name='Régimen Tributario'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='resolucion_dian',
            field=models.CharField(default='RES-DIAN-2024-001', help_text='Número de resolución de facturación', max_length=50, verbose_name='Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
    ]
