# Generated by Django 5.0 on 2026-03-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_aplica_impuesto_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='rango_hasta',
            field=models.IntegerField(default=19445578, help_text='Número final autorizado', verbose_name='Rango Hasta'),
        ),
    ]
