# Generated by Django 5.0 on 2026-01-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('usuarios', '0002_usuario_notificado_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.sucursal', verbose_name='Sucursal asignada'),
        ),
    ]
