# Generated by Django 5.0 on 2026-01-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMIN', '👑 Super Administrador '), ('ADMIN', '👨\u200d💼 Administrador'), ('EMPLEADO', '👤 Empleado'), ('AUDITOR', '👁️ Auditor/Contador')], default='EMPLEADO', max_length=20, verbose_name='Rol'),
        ),
    ]
