# Generated by Django 5.0 on 2026-02-03 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_remove_factura_cliente_remove_detallefactura_factura_and_more'),
        ('sucursales', '0002_sucursal_aplica_impuesto_consumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo / Razón Social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'inventario_cliente',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('prefijo', models.CharField(default='FAC', max_length=10, verbose_name='Prefijo')),
                ('consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (sin impuestos)')),
                ('impuesto_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto al Consumo (8%)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total a Pagar')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TARJETA_DEBITO', '💳 Tarjeta Débito'), ('TARJETA_CREDITO', '💳 Tarjeta Crédito'), ('TRANSFERENCIA', '🏦 Transferencia Bancaria'), ('NEQUI', '📱 Nequi'), ('DAVIPLATA', '📱 Daviplata'), ('CREDITO', '📋 Crédito'), ('OTRO', '🔄 Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Recibido')),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Solo para ventas a crédito', null=True, verbose_name='Fecha de Vencimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('enviada_por_email', models.BooleanField(default=False, verbose_name='Enviada por Email')),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío Email')),
                ('anulada', models.BooleanField(default=False, verbose_name='Factura Anulada')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='Motivo de Anulación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturas.cliente', verbose_name='Cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='sucursales.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'inventario_factura',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'inventario_detallefactura',
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_c771c3_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='inventario__numero__f8b607_idx'),
        ),
    ]
