# Generated by Django 5.0 on 2026-03-10 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0008_movimientoinventario_factura'),
        ('proveedores', '0002_proveedor_cantidad_minima_pedido_and_more'),
        ('sucursales', '0003_alter_sucursal_rango_hasta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_cobertura_default', models.IntegerField(default=30, help_text='Stock para cuántos días mantener', verbose_name='Días de Cobertura por Defecto')),
                ('stock_seguridad_porcentaje', models.IntegerField(default=20, help_text='Porcentaje adicional de seguridad', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Stock de Seguridad (%)')),
                ('dias_analisis_historico', models.IntegerField(default=90, help_text='Cuántos días atrás analizar ventas', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)], verbose_name='Días de Histórico para Análisis')),
                ('umbral_urgente_dias', models.IntegerField(default=3, help_text='Stock para menos de X días = URGENTE', verbose_name='Umbral URGENTE (días)')),
                ('umbral_alta_dias', models.IntegerField(default=7, help_text='Stock para menos de X días = ALTA', verbose_name='Umbral ALTA (días)')),
                ('umbral_media_dias', models.IntegerField(default=15, help_text='Stock para menos de X días = MEDIA', verbose_name='Umbral MEDIA (días)')),
                ('habilitar_ia', models.BooleanField(default=True, help_text='Usar Prophet para predicciones', verbose_name='Habilitar Predicción con IA')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Compras',
                'verbose_name_plural': 'Configuraciones de Compras',
            },
        ),
        migrations.CreateModel(
            name='SugerenciaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo Configurado')),
                ('promedio_ventas_diarias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Promedio Ventas Diarias')),
                ('dias_stock_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Días de Stock Restante')),
                ('prediccion_proximos_30_dias', models.IntegerField(default=0, help_text='Calculado con Prophet', verbose_name='Predicción Ventas 30 Días (IA)')),
                ('tendencia', models.CharField(choices=[('CRECIENTE', '📈 Ventas Aumentando'), ('ESTABLE', '➡️ Ventas Estables'), ('DECRECIENTE', '📉 Ventas Disminuyendo')], default='ESTABLE', max_length=20, verbose_name='Tendencia de Ventas')),
                ('cantidad_sugerida', models.IntegerField(default=0, verbose_name='Cantidad Sugerida a Comprar')),
                ('punto_reorden', models.IntegerField(default=0, help_text='Stock en el que se debe pedir', verbose_name='Punto de Reorden')),
                ('dias_cobertura_deseada', models.IntegerField(default=30, verbose_name='Días de Cobertura Deseada')),
                ('urgencia', models.CharField(choices=[('URGENTE', '🔴 URGENTE - Stock crítico'), ('ALTA', '🟠 ALTA - Stock bajo'), ('MEDIA', '🟡 MEDIA - Planificar'), ('BAJA', '🟢 BAJA - Stock suficiente')], default='MEDIA', max_length=20, verbose_name='Nivel de Urgencia')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Unitario')),
                ('inversion_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Inversión Estimada Total')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('razon', models.TextField(blank=True, verbose_name='Razón de la Sugerencia')),
                ('confianza_ia', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confianza del Modelo IA (%)')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado Por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_compra', to='inventario.producto', verbose_name='Producto')),
                ('proveedor_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to='proveedores.proveedor', verbose_name='Proveedor Sugerido')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_compra', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Sugerencia de Compra',
                'verbose_name_plural': 'Sugerencias de Compra',
                'ordering': ['urgencia', '-dias_stock_restante'],
                'indexes': [models.Index(fields=['urgencia', 'fecha_generacion'], name='compras_sug_urgenci_ca1875_idx'), models.Index(fields=['sucursal', 'urgencia'], name='compras_sug_sucursa_7bfda8_idx')],
            },
        ),
    ]
