# Generated by Django 5.0 on 2026-03-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0010_alter_producto_clase_abc'),
        ('sucursales', '0003_alter_sucursal_rango_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachePrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion', models.IntegerField()),
                ('confianza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tendencia', models.CharField(max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
            options={
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
