# Generated by Django 5.0 on 2026-03-10 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cantidad_minima_pedido',
            field=models.IntegerField(default=1, help_text='Cantidad mínima que acepta por pedido', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Mínima de Pedido'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_volumen',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento si se compra en grandes cantidades', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento por Volumen (%)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_entrega',
            field=models.IntegerField(default=7, help_text='Tiempo que tarda en entregar después del pedido', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de Entrega'),
        ),
    ]
