# Generated by Django 5.0 on 2026-02-22 02:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre que aparecerá en el sistema', max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(db_index=True, help_text='Número de Identificación Tributaria', max_length=20, unique=True, verbose_name='NIT')),
                ('slug', models.SlugField(help_text='Identificador único para URLs (ej: mi-empresa)', max_length=100, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(choices=[('BASICO', 'Plan Básico - $38.900/mes'), ('EMPRENDEDOR', 'Plan Emprendedor - $79.000/mes'), ('PROFESIONAL', 'Plan Profesional - $189.000/mes'), ('ENTERPRISE', 'Plan Enterprise - Personalizado')], default='BASICO', max_length=20, verbose_name='Plan Contratado')),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Si está desactivada, los usuarios no podrán acceder', verbose_name='Empresa Activa')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Dejar vacío para plan ilimitado', null=True, verbose_name='Fecha de Vencimiento del Plan')),
                ('limite_usuarios', models.IntegerField(default=2, help_text='Cantidad máxima de usuarios activos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Usuarios')),
                ('limite_sucursales', models.IntegerField(default=1, help_text='Cantidad máxima de sucursales', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Sucursales')),
                ('limite_productos', models.IntegerField(default=300, help_text='Cantidad máxima de productos en inventario', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Productos')),
                ('email_admin', models.EmailField(help_text='Email principal de contacto', max_length=254, verbose_name='Email del Administrador')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo de la Empresa')),
                ('color_primario', models.CharField(default='#667eea', help_text='Color en formato hexadecimal (ej: #667eea)', max_length=7, verbose_name='Color Primario')),
                ('notas_internas', models.TextField(blank=True, help_text='Solo visible para SuperAdmin', verbose_name='Notas Internas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VENTA', 'Venta realizada'), ('TRANSFERENCIA', 'Transferencia entre sucursales'), ('CAMBIO_PRECIO', 'Cambio de precio'), ('AJUSTE_INVENTARIO', 'Ajuste de inventario'), ('ANULAR_FACTURA', 'Anulación de factura')], max_length=50, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Nombre del modelo (ej: Producto, Venta)', max_length=100, verbose_name='Modelo Afectado')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Detalles')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y dispositivo usado', verbose_name='User Agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['slug'], name='empresas_em_slug_8f8394_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nit'], name='empresas_em_nit_ac5873_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activa', '-fecha_creacion'], name='empresas_em_activa_023da6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['empresa', '-fecha'], name='empresas_au_empresa_adf9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario', '-fecha'], name='empresas_au_usuario_fed95a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['accion', '-fecha'], name='empresas_au_accion_e022ed_idx'),
        ),
    ]
